addSbtPlugin("com.github.gseitz"  % "sbt-release"         % "1.0.12")
addSbtPlugin("com.jsuereth"       % "sbt-pgp"             % "2.0.0")
addSbtPlugin("org.scalariform"    % "sbt-scalariform"     % "1.8.3")
addSbtPlugin("org.scoverage"      % "sbt-coveralls"       % "1.2.7")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"        % "3.8.1")
